#!/usr/bin/env python3
"""
Convert the MySQL schema (files/schema.sql) into PostgreSQL DDL.

Kept as a repeatable script rather than a one-off hand edit so schema.sql stays
the single source of truth: change schema.sql, re-run this, get schema.pgsql.sql.

Mapping decisions
  INT UNSIGNED AUTO_INCREMENT PK -> INTEGER GENERATED BY DEFAULT AS IDENTITY
      ("BY DEFAULT" so seed rows may still supply explicit ids)
  INT/SMALLINT/TINYINT UNSIGNED  -> INTEGER / INTEGER / SMALLINT  (no unsigned in PG)
  TINYINT(1)                     -> SMALLINT   (not BOOLEAN: the app compares `= 1`)
  DATETIME                       -> TIMESTAMP
  NOW()                          -> CURRENT_TIMESTAMP
  ON UPDATE NOW()                -> dropped; replaced by a shared touch trigger
  ENUM(...)                      -> VARCHAR + CHECK (... IN ...)
  SET(...)                       -> VARCHAR  (app stores a comma-joined list)
  JSON                           -> JSONB    (all writes go through json_encode)
  inline INDEX/UNIQUE KEY        -> separate CREATE INDEX statements
  ENGINE=/DEFAULT CHARSET=       -> dropped
"""
import re
import sys
import pathlib

SRC = pathlib.Path(__file__).resolve().parent.parent / 'schema.sql'
DST = pathlib.Path(__file__).resolve().parent.parent / 'schema.pgsql.sql'

TOUCH_FN = """
-- Shared trigger function replacing MySQL's `ON UPDATE NOW()` column clause.
CREATE OR REPLACE FUNCTION touch_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
""".strip()


def convert_type(col: str, colname: str, table: str, checks: list) -> str:
    """Translate one column definition's type + attributes."""
    c = col

    # ENUM / SET -> VARCHAR (+ CHECK for ENUM)
    m = re.search(r"\bENUM\s*\(([^)]*)\)", c, re.I)
    if m:
        vals = m.group(1)
        width = max(len(v.strip().strip("'")) for v in vals.split(',')) + 10
        c = c[:m.start()] + f"VARCHAR({width})" + c[m.end():]
        checks.append(f"CHECK ({colname} IN ({vals}))")
    m = re.search(r"\bSET\s*\(([^)]*)\)", c, re.I)
    if m:
        vals = m.group(1)
        width = sum(len(v.strip()) for v in vals.split(',')) + 10
        c = c[:m.start()] + f"VARCHAR({width})" + c[m.end():]

    # Integer widths — order matters (longest first).
    c = re.sub(r"\bBIGINT\s+UNSIGNED\b", "BIGINT", c, flags=re.I)
    c = re.sub(r"\bINT\s+UNSIGNED\b", "INTEGER", c, flags=re.I)
    c = re.sub(r"\bSMALLINT\s+UNSIGNED\b", "INTEGER", c, flags=re.I)
    c = re.sub(r"\bTINYINT\s+UNSIGNED\b", "SMALLINT", c, flags=re.I)
    c = re.sub(r"\bMEDIUMINT\s+UNSIGNED\b", "INTEGER", c, flags=re.I)
    c = re.sub(r"\bTINYINT\s*\(\s*\d+\s*\)", "SMALLINT", c, flags=re.I)
    c = re.sub(r"\bTINYINT\b", "SMALLINT", c, flags=re.I)
    c = re.sub(r"\bMEDIUMINT\b", "INTEGER", c, flags=re.I)
    c = re.sub(r"\bINT\s*\(\s*\d+\s*\)", "INTEGER", c, flags=re.I)

    # Text / date / json types
    c = re.sub(r"\b(LONGTEXT|MEDIUMTEXT|TINYTEXT)\b", "TEXT", c, flags=re.I)
    c = re.sub(r"\bDATETIME\b", "TIMESTAMP", c, flags=re.I)
    c = re.sub(r"\bYEAR\b(?!\s*\()", "SMALLINT", c, flags=re.I)   # MySQL YEAR type
    c = re.sub(r"\bJSON\b", "JSONB", c, flags=re.I)

    # Defaults / auto-update
    c = re.sub(r"ON\s+UPDATE\s+(NOW\(\)|CURRENT_TIMESTAMP)", "", c, flags=re.I)
    c = re.sub(r"\bNOW\(\)", "CURRENT_TIMESTAMP", c, flags=re.I)

    # Generated columns: MySQL VIRTUAL/STORED -> Postgres STORED (PG has no VIRTUAL).
    if re.search(r"GENERATED\s+ALWAYS\s+AS", c, re.I):
        c = re.sub(r"\bVIRTUAL\b", "STORED", c, flags=re.I)
        if not re.search(r"\bSTORED\b", c, re.I):
            c = c.rstrip() + " STORED"

    # Identity column
    if re.search(r"\bAUTO_INCREMENT\b", c, re.I):
        c = re.sub(r"\bAUTO_INCREMENT\b", "GENERATED BY DEFAULT AS IDENTITY", c, flags=re.I)
        # INTEGER GENERATED ... must not also carry a DEFAULT
        c = re.sub(r"DEFAULT\s+\S+\s+(?=GENERATED)", "", c, flags=re.I)

    return re.sub(r"\s+", " ", c).strip()


def convert(sql: str) -> str:
    out, indexes = [], []
    out.append("-- Generated by tools/mysql2pg.py — do not edit by hand.")
    out.append("-- Source of truth: schema.sql (MySQL). Re-run the script after changes.\n")
    out.append(TOUCH_FN + "\n")

    # Drop MySQL session pragmas.
    sql = re.sub(r"^\s*SET\s+(NAMES|foreign_key_checks)\b.*$", "", sql, flags=re.I | re.M)
    # MySQL backtick quoting -> bare identifiers (all names here are valid
    # unquoted in Postgres, incl. `condition`, so queries need no quoting).
    sql = sql.replace('`', '')

    pos = 0
    touch_tables = []
    for m in re.finditer(r"CREATE TABLE\s+(\w+)\s*\((.*?)\n\)\s*ENGINE=[^;]*;", sql, re.S | re.I):
        out.append(sql[pos:m.start()].rstrip())
        pos = m.end()
        table, body = m.group(1), m.group(2)
        checks, cols = [], []
        needs_touch = False

        for raw in body.split('\n'):
            line = raw.strip()
            if not line:
                continue
            comment = ''
            cm = re.search(r"\s--\s.*$", line)
            if cm:
                comment = '  ' + cm.group(0).strip()
                line = line[:cm.start()].strip()
            if not line or line.startswith('--'):
                continue
            trailing_comma = line.endswith(',')
            line = line.rstrip(',').strip()
            if not line:
                continue

            up = line.upper()
            # Inline indexes -> standalone CREATE INDEX
            im = re.match(r"(UNIQUE\s+)?(?:KEY|INDEX)\s+(\w+)\s*\(([^)]*)\)$", line, re.I)
            if im:
                uniq = 'UNIQUE ' if im.group(1) else ''
                cols_ = re.sub(r"\(\d+\)", "", im.group(3))  # drop prefix lengths
                indexes.append(f"CREATE {uniq}INDEX {table}_{im.group(2)} ON {table} ({cols_});")
                continue
            if up.startswith(('PRIMARY KEY', 'FOREIGN KEY', 'CONSTRAINT', 'UNIQUE (', 'CHECK ')):
                cols.append((line, comment))
                continue

            cname = line.split()[0]
            if re.search(r"ON\s+UPDATE\s+(NOW\(\)|CURRENT_TIMESTAMP)", line, re.I):
                needs_touch = True
            cols.append((convert_type(line, cname, table, checks), comment))

        for ck in checks:
            cols.append((ck, ''))

        # Comma belongs to the definition, not after the comment — otherwise the
        # comment swallows it and the statement breaks.
        body_lines = [
            '  ' + text + (',' if i < len(cols) - 1 else '') + comment
            for i, (text, comment) in enumerate(cols)
        ]
        out.append(f"CREATE TABLE {table} (\n" + '\n'.join(body_lines) + "\n);")
        if needs_touch:
            touch_tables.append(table)

    out.append(sql[pos:])

    if indexes:
        out.append("\n-- Indexes (inline in MySQL, standalone in Postgres)")
        out.extend(indexes)

    if touch_tables:
        out.append("\n-- updated_at triggers (MySQL's ON UPDATE NOW())")
        for t in touch_tables:
            out.append(
                f"CREATE TRIGGER {t}_touch BEFORE UPDATE ON {t} "
                f"FOR EACH ROW EXECUTE FUNCTION touch_updated_at();"
            )

    text = '\n'.join(out)
    # MySQL escapes a quote as \' — Postgres uses ''.
    text = text.replace("\\'", "''")
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text


def main() -> int:
    sql = SRC.read_text(encoding='utf-8')
    DST.write_text(convert(sql), encoding='utf-8')
    print(f"wrote {DST}")
    return 0


if __name__ == '__main__':
    sys.exit(main())
