-- Generated by tools/mysql2pg.py — do not edit by hand.
-- Source of truth: schema.sql (MySQL). Re-run the script after changes.

-- Shared trigger function replacing MySQL's `ON UPDATE NOW()` column clause.
CREATE OR REPLACE FUNCTION touch_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================================================
-- Integra Repair & RMA Management System
-- Complete Database Schema — v1.0
-- 63 tables across 16 domains
-- ============================================================

-- ============================================================
-- DOMAIN 1: IDENTITY & AUTH (7)
-- ============================================================
CREATE TABLE locations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  code VARCHAR(10),  -- short prefix used for RMA numbering (HQ, PG, BD…)
  address VARCHAR(255),
  postal_code VARCHAR(20),
  city VARCHAR(100),
  country VARCHAR(100) DEFAULT 'Montenegro',
  phone VARCHAR(30),
  email VARCHAR(150),
  is_active SMALLINT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP DEFAULT NULL
);

CREATE TABLE users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  location_id INTEGER DEFAULT NULL,
  name VARCHAR(150) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  phone VARCHAR(30),
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(21) NOT NULL,
  lang VARCHAR(10) DEFAULT 'en',
  theme VARCHAR(30) DEFAULT 'midnight',
  is_active SMALLINT DEFAULT 1,
  last_login TIMESTAMP DEFAULT NULL,
  password_changed_at TIMESTAMP DEFAULT NULL,
  must_change_pw SMALLINT DEFAULT 0,
  require_2fa SMALLINT DEFAULT 0,
  preferred_2fa_channel VARCHAR(10) DEFAULT NULL,
  totp_secret VARCHAR(64) DEFAULT NULL,
  totp_confirmed_at TIMESTAMP DEFAULT NULL,
  access_scope VARCHAR(10) NOT NULL DEFAULT 'any',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP DEFAULT NULL,
  archived_at TIMESTAMP DEFAULT NULL,
  FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE SET NULL,
  CHECK (role IN ('super_admin','admin','reception','technician','partner'))
);

CREATE TABLE security_policies (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role VARCHAR(21) UNIQUE NOT NULL,
  require_2fa SMALLINT DEFAULT 0,
  allowed_2fa_channels VARCHAR(32) DEFAULT 'email',
  max_login_attempts SMALLINT DEFAULT 5,
  lockout_minutes INTEGER DEFAULT 30,
  password_min_length SMALLINT DEFAULT 10,
  password_expiry_days INTEGER DEFAULT NULL,
  session_timeout_min INTEGER DEFAULT 480,
  force_2fa_new_device SMALLINT DEFAULT 1,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CHECK (role IN ('super_admin','admin','reception','technician','partner'))
);

CREATE TABLE otp_codes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL,
  code_hash VARCHAR(255) NOT NULL,
  channel VARCHAR(18) NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  attempts SMALLINT DEFAULT 0,
  used SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CHECK (channel IN ('email','whatsapp','sms'))
);

CREATE TABLE auth_attempts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  identifier VARCHAR(255),
  ip_address VARCHAR(45),
  success SMALLINT DEFAULT 0,
  blocked SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE auth_log (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER DEFAULT NULL,
  ip_address VARCHAR(45),
  user_agent TEXT,
  channel_2fa VARCHAR(18) DEFAULT 'none',
  success SMALLINT DEFAULT 0,
  fail_reason VARCHAR(100),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CHECK (channel_2fa IN ('email','whatsapp','sms','none'))
);

CREATE TABLE trusted_devices (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL,
  device_hash VARCHAR(255) NOT NULL,
  user_agent VARCHAR(500),
  ip_address VARCHAR(45),
  last_seen TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- ============================================================
-- DOMAIN 2: PARTNERS & CUSTOMERS (5)
-- ============================================================
CREATE TABLE customers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  email VARCHAR(150),
  phone VARCHAR(30),
  address VARCHAR(255),
  city VARCHAR(100),
  zip_code VARCHAR(30),
  country VARCHAR(100),
  notes TEXT,
  lang VARCHAR(2) NOT NULL DEFAULT 'me',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP DEFAULT NULL,
  archived_at TIMESTAMP DEFAULT NULL
);

CREATE TABLE partners (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  tax_id VARCHAR(50),
  email VARCHAR(150),
  phone VARCHAR(30),
  address VARCHAR(255),
  zip_code VARCHAR(30),
  city VARCHAR(100),
  country VARCHAR(100),
  contact_person VARCHAR(150),
  notes TEXT,
  default_courier_id INTEGER DEFAULT NULL,  -- preferred courier (FK added after couriers table)
  is_active SMALLINT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP DEFAULT NULL
);

CREATE TABLE partner_users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  partner_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  role VARCHAR(15) DEFAULT 'staff',
  invited_by INTEGER DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (partner_id) REFERENCES partners(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CHECK (role IN ('admin','staff'))
);

CREATE TABLE api_tokens (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL,
  partner_id INTEGER NOT NULL,
  token_hash VARCHAR(255) NOT NULL UNIQUE,
  label VARCHAR(100),
  last_used TIMESTAMP DEFAULT NULL,
  expires_at TIMESTAMP DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  revoked_at TIMESTAMP DEFAULT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (partner_id) REFERENCES partners(id) ON DELETE CASCADE
);

CREATE TABLE service_contracts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  partner_id INTEGER NOT NULL,
  name VARCHAR(150),
  start_date DATE NOT NULL,
  end_date DATE,
  billing_cycle VARCHAR(19) DEFAULT 'monthly',
  billing_amount DECIMAL(10,2),
  currency VARCHAR(3) DEFAULT 'EUR',
  sla_response_hrs INTEGER DEFAULT 24,
  sla_resolution_hrs INTEGER DEFAULT 72,
  notes TEXT,
  is_active SMALLINT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP DEFAULT NULL,
  FOREIGN KEY (partner_id) REFERENCES partners(id) ON DELETE RESTRICT,
  CHECK (billing_cycle IN ('monthly','quarterly','annual'))
);

-- ============================================================
-- DOMAIN 3: DEVICE CATALOG (4)
-- ============================================================
CREATE TABLE device_categories (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  sku_prefix VARCHAR(6) DEFAULT NULL,  -- used by helpers/sku.php for part SKU generation
  slug VARCHAR(100) NOT NULL UNIQUE,
  sort_order SMALLINT DEFAULT 0,
  is_active SMALLINT DEFAULT 1
);

CREATE TABLE device_brands (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vendor_id INTEGER DEFAULT NULL,
  name VARCHAR(100) NOT NULL,
  slug VARCHAR(100) NOT NULL UNIQUE,
  logo_path VARCHAR(500),
  is_active SMALLINT DEFAULT 1
);

CREATE TABLE device_models (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brand_id INTEGER NOT NULL,
  category_id INTEGER NOT NULL,
  vendor_id INTEGER DEFAULT NULL,
  name VARCHAR(150) NOT NULL,
  model_number VARCHAR(100),
  release_year SMALLINT,
  is_active SMALLINT DEFAULT 1,
  FOREIGN KEY (brand_id) REFERENCES device_brands(id),
  FOREIGN KEY (category_id) REFERENCES device_categories(id)
);

CREATE TABLE devices (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  model_id INTEGER NOT NULL,
  customer_id INTEGER DEFAULT NULL,
  partner_id INTEGER DEFAULT NULL,
  serial_number VARCHAR(100),
  imei VARCHAR(20),
  purchase_date DATE DEFAULT NULL,
  warranty_expiry DATE DEFAULT NULL,
  color VARCHAR(50),
  capacity VARCHAR(30),
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (model_id) REFERENCES device_models(id),
  FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL,
  FOREIGN KEY (partner_id) REFERENCES partners(id) ON DELETE SET NULL
);

-- ============================================================
-- DOMAIN 4: RMA CORE (6)
-- ============================================================
CREATE TABLE rma_statuses (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(60) NOT NULL UNIQUE,
  label VARCHAR(100) NOT NULL,
  label_me VARCHAR(100) NULL,
  color VARCHAR(20),
  sort_order SMALLINT DEFAULT 0,
  is_terminal SMALLINT DEFAULT 0,
  is_system SMALLINT DEFAULT 1
);

CREATE TABLE rma_requests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  location_id INTEGER NOT NULL,
  device_id INTEGER DEFAULT NULL,
  customer_id INTEGER DEFAULT NULL,
  partner_id INTEGER DEFAULT NULL,
  submitted_by INTEGER DEFAULT NULL,
  assigned_tech INTEGER DEFAULT NULL,
  status_id INTEGER NOT NULL,
  vendor_id INTEGER DEFAULT NULL,
  vendor_ra_number VARCHAR(100) DEFAULT NULL,
  vendor_rma_ref VARCHAR(100) DEFAULT NULL,
  vendor_warranty_status VARCHAR(21) DEFAULT 'unknown',
  vendor_last_sync TIMESTAMP DEFAULT NULL,
  rma_number VARCHAR(30) NOT NULL UNIQUE,
  complaint TEXT,
  diagnosis TEXT,
  service_box VARCHAR(100) DEFAULT NULL,
  accessories JSONB DEFAULT NULL,
  accessories_other VARCHAR(255) DEFAULT NULL,
  is_warranty SMALLINT DEFAULT 0,
  warranty_refusal JSONB DEFAULT NULL,
  priority VARCHAR(16) DEFAULT 'normal',
  sla_rule_id INTEGER DEFAULT NULL,
  sla_due_at TIMESTAMP DEFAULT NULL,
  sla_breached SMALLINT DEFAULT 0,
  estimated_completion DATE DEFAULT NULL,
  completed_at TIMESTAMP DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP DEFAULT NULL,
  archived_at TIMESTAMP DEFAULT NULL,
  FOREIGN KEY (location_id) REFERENCES locations(id),
  FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE SET NULL,
  FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL,
  FOREIGN KEY (partner_id) REFERENCES partners(id) ON DELETE SET NULL,
  FOREIGN KEY (status_id) REFERENCES rma_statuses(id),
  FOREIGN KEY (assigned_tech) REFERENCES users(id) ON DELETE SET NULL,
  CHECK (vendor_warranty_status IN ('covered','not_covered','expired','unknown')),
  CHECK (priority IN ('low','normal','high','urgent'))
);

-- Hands out RMA numbers atomically. scope is 'global' (never resets) or the
-- four-digit year (restarts each January), chosen by rma_number_reset_yearly.
-- next_value is the number that will be issued next.
CREATE TABLE rma_counters (
  scope VARCHAR(20) NOT NULL PRIMARY KEY,
  next_value INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE rma_status_history (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rma_id INTEGER NOT NULL,
  status_id INTEGER NOT NULL,
  changed_by INTEGER DEFAULT NULL,
  note TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (rma_id) REFERENCES rma_requests(id) ON DELETE CASCADE,
  FOREIGN KEY (status_id) REFERENCES rma_statuses(id)
);

CREATE TABLE rma_comments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rma_id INTEGER NOT NULL,
  user_id INTEGER DEFAULT NULL,
  body TEXT NOT NULL,
  visibility VARCHAR(18) DEFAULT 'internal',
  source VARCHAR(18) NOT NULL DEFAULT 'staff',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP DEFAULT NULL,
  FOREIGN KEY (rma_id) REFERENCES rma_requests(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  CHECK (visibility IN ('internal','customer')),
  CHECK (source IN ('staff','customer'))
);

CREATE TABLE rma_attachments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rma_id INTEGER NOT NULL,
  uploaded_by INTEGER DEFAULT NULL,
  file_type VARCHAR(22) NOT NULL,
  original_name VARCHAR(255),
  original_size INTEGER,
  processed_size INTEGER,
  file_path VARCHAR(500) NOT NULL,
  thumbnail_path VARCHAR(500),
  mime_type VARCHAR(100),
  width INTEGER DEFAULT NULL,
  height INTEGER DEFAULT NULL,
  is_processed SMALLINT DEFAULT 0,
  processed_at TIMESTAMP DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP DEFAULT NULL,
  FOREIGN KEY (rma_id) REFERENCES rma_requests(id) ON DELETE CASCADE,
  FOREIGN KEY (uploaded_by) REFERENCES users(id) ON DELETE SET NULL,
  CHECK (file_type IN ('intake_photo','repair_photo','evidence','document'))
);

CREATE TABLE rma_tracking_tokens (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rma_id INTEGER NOT NULL UNIQUE,
  token VARCHAR(64) NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (rma_id) REFERENCES rma_requests(id) ON DELETE CASCADE
);

-- ============================================================
-- DOMAIN 5: REPAIR JOBS & TIME (3)
-- ============================================================
CREATE TABLE repair_statuses (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(60) NOT NULL UNIQUE,
  label VARCHAR(100) NOT NULL,
  label_me VARCHAR(100) NULL,
  color VARCHAR(20),
  sort_order SMALLINT DEFAULT 0,
  is_terminal SMALLINT DEFAULT 0
);

CREATE TABLE repair_jobs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rma_id INTEGER NOT NULL,
  location_id INTEGER NOT NULL,
  technician_id INTEGER DEFAULT NULL,
  status_id INTEGER NOT NULL,
  description TEXT,
  resolution TEXT,
  started_at TIMESTAMP DEFAULT NULL,
  completed_at TIMESTAMP DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP DEFAULT NULL,
  FOREIGN KEY (rma_id) REFERENCES rma_requests(id) ON DELETE CASCADE,
  FOREIGN KEY (location_id) REFERENCES locations(id),
  FOREIGN KEY (technician_id) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (status_id) REFERENCES repair_statuses(id)
);

CREATE TABLE repair_time_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  minutes INTEGER NOT NULL,
  note VARCHAR(255),
  logged_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (job_id) REFERENCES repair_jobs(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- ============================================================
-- DOMAIN 6: LOANER DEVICES (2)
-- ============================================================
CREATE TABLE loaner_devices (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  location_id INTEGER NOT NULL,
  model_id INTEGER DEFAULT NULL,
  serial_number VARCHAR(100),
  label VARCHAR(100),
  condition VARCHAR(14) DEFAULT 'good',
  notes TEXT,
  is_active SMALLINT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP DEFAULT NULL,
  FOREIGN KEY (location_id) REFERENCES locations(id),
  FOREIGN KEY (model_id) REFERENCES device_models(id) ON DELETE SET NULL,
  CHECK (condition IN ('new','good','fair','poor'))
);

CREATE TABLE loaner_assignments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  loaner_id INTEGER NOT NULL,
  rma_id INTEGER NOT NULL,
  customer_id INTEGER DEFAULT NULL,
  assigned_by INTEGER DEFAULT NULL,
  assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  returned_at TIMESTAMP DEFAULT NULL,
  condition_out VARCHAR(14) DEFAULT 'good',
  condition_in VARCHAR(14) DEFAULT NULL,
  notes TEXT,
  FOREIGN KEY (loaner_id) REFERENCES loaner_devices(id),
  FOREIGN KEY (rma_id) REFERENCES rma_requests(id) ON DELETE CASCADE,
  FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL,
  FOREIGN KEY (assigned_by) REFERENCES users(id) ON DELETE SET NULL,
  CHECK (condition_out IN ('new','good','fair','poor')),
  CHECK (condition_in IN ('new','good','fair','poor'))
);

-- ============================================================
-- DOMAIN 7: PARTS & SUPPLIERS (6)
-- ============================================================
CREATE TABLE suppliers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  contact VARCHAR(150),
  email VARCHAR(150),
  phone VARCHAR(30),
  address VARCHAR(255),
  city VARCHAR(100),
  zip_code VARCHAR(30),
  country VARCHAR(100),
  notes TEXT,
  is_active SMALLINT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP DEFAULT NULL
);

CREATE TABLE part_groups (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  slug VARCHAR(100) NOT NULL UNIQUE,
  sort_order INTEGER DEFAULT 0,
  is_active SMALLINT DEFAULT 1
);

INSERT INTO part_groups (name, slug, sort_order) VALUES
  ('Battery',            'battery',         10),
  ('LCD / Display',      'display',         20),
  ('Touch / Digitizer',  'digitizer',       25),
  ('Camera',             'camera',          30),
  ('Speaker / Earpiece', 'speaker',         40),
  ('Microphone',         'microphone',      45),
  ('Motherboard',        'motherboard',     50),
  ('Charging port',      'charging-port',   60),
  ('Buttons',            'buttons',         70),
  ('Frame / Housing',    'frame',           80),
  ('Cable / Flex',       'cable',           90),
  ('Antenna',            'antenna',        100),
  ('SIM tray',           'sim-tray',       110),
  ('Back glass / Cover', 'back-glass',     120),
  ('Adhesive',           'adhesive',       200),
  ('Screws / Fasteners', 'screws',         210),
  ('Tools',              'tools',          220),
  ('Consumable',         'consumable',     230),
  ('Other',              'other',          900);
CREATE TABLE parts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supplier_id INTEGER DEFAULT NULL,
  brand_id INTEGER DEFAULT NULL,  -- NULL = any brand (universal)
  category_id INTEGER DEFAULT NULL,  -- NULL = any device kind (phones/tablets/…)
  part_group_id INTEGER DEFAULT NULL,  -- NULL = unclassified part taxonomy
  name VARCHAR(150) NOT NULL,
  internal_sku VARCHAR(100) UNIQUE,  -- auto-generated (helpers/sku.php)
  supplier_sku VARCHAR(100) DEFAULT NULL,  -- vendor's part number
  description TEXT,
  unit_price DECIMAL(10,2) DEFAULT 0.00,  -- retail / sell price
  cost_price DECIMAL(10,4) DEFAULT 0.0000,  -- weighted-average purchase cost (updated on goods-receipt confirm)
  vat_rate_id INTEGER DEFAULT NULL,
  min_stock INTEGER DEFAULT 5,  -- reorder threshold
  is_active SMALLINT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP DEFAULT NULL,
  FOREIGN KEY (supplier_id)   REFERENCES suppliers(id)         ON DELETE SET NULL,
  FOREIGN KEY (brand_id)      REFERENCES device_brands(id)     ON DELETE SET NULL,
  FOREIGN KEY (category_id)   REFERENCES device_categories(id) ON DELETE SET NULL,
  FOREIGN KEY (part_group_id) REFERENCES part_groups(id)       ON DELETE SET NULL
);

CREATE TABLE parts_stock (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  part_id INTEGER NOT NULL,
  location_id INTEGER NOT NULL,
  quantity INTEGER DEFAULT 0,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (part_id) REFERENCES parts(id) ON DELETE CASCADE,
  FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE CASCADE
);

CREATE TABLE part_usage (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id INTEGER NOT NULL,
  part_id INTEGER NOT NULL,
  location_id INTEGER NOT NULL,
  quantity INTEGER DEFAULT 1,
  unit_cost DECIMAL(10,2),  -- cost snapshot at time of usage
  logged_by INTEGER DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (job_id) REFERENCES repair_jobs(id) ON DELETE CASCADE,
  FOREIGN KEY (part_id) REFERENCES parts(id),
  FOREIGN KEY (location_id) REFERENCES locations(id),
  FOREIGN KEY (logged_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE purchase_orders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supplier_id INTEGER NOT NULL,
  location_id INTEGER NOT NULL,
  created_by INTEGER DEFAULT NULL,
  status VARCHAR(19) DEFAULT 'draft',
  po_number VARCHAR(50) UNIQUE,
  notes TEXT,
  ordered_at TIMESTAMP DEFAULT NULL,
  received_at TIMESTAMP DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP DEFAULT NULL,
  FOREIGN KEY (supplier_id) REFERENCES suppliers(id),
  FOREIGN KEY (location_id) REFERENCES locations(id),
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CHECK (status IN ('draft','sent','received','cancelled'))
);

CREATE TABLE purchase_order_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER NOT NULL,
  part_id INTEGER NOT NULL,
  quantity INTEGER NOT NULL,
  unit_price DECIMAL(10,2),
  received_qty INTEGER DEFAULT 0,
  FOREIGN KEY (order_id) REFERENCES purchase_orders(id) ON DELETE CASCADE,
  FOREIGN KEY (part_id) REFERENCES parts(id)
);

-- ============================================================
-- DOMAIN 8: DELIVERY (2)
-- ============================================================
CREATE TABLE couriers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  slug VARCHAR(60) NOT NULL UNIQUE,
  api_class VARCHAR(150),
  tracking_url VARCHAR(500),
  phone VARCHAR(60) DEFAULT NULL,
  is_active SMALLINT DEFAULT 1
);

INSERT INTO couriers (name, slug, tracking_url, is_active) VALUES
  ('Pošta Crne Gore', 'posta-cg',  'https://www.postacg.me/track?id={tracking}',       1),
  ('DHL',             'dhl',       'https://www.dhl.com/track?tracking-id={tracking}', 1),
  ('Ručna dostava',   'in-person', NULL, 1);
CREATE TABLE delivery_shipments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rma_id INTEGER NOT NULL,
  courier_id INTEGER DEFAULT NULL,
  location_id INTEGER DEFAULT NULL,
  direction VARCHAR(18) DEFAULT 'inbound',
  tracking_number VARCHAR(150),
  label_path VARCHAR(500),
  status VARCHAR(100) DEFAULT 'pending',
  carrier_status VARCHAR(255),
  cost DECIMAL(10,2) DEFAULT NULL,
  notes VARCHAR(500) DEFAULT NULL,
  dispatched_at TIMESTAMP DEFAULT NULL,
  delivered_at TIMESTAMP DEFAULT NULL,
  last_polled_at TIMESTAMP DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (rma_id) REFERENCES rma_requests(id) ON DELETE CASCADE,
  FOREIGN KEY (courier_id) REFERENCES couriers(id) ON DELETE SET NULL,
  FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE SET NULL,
  CHECK (direction IN ('inbound','outbound'))
);

-- ============================================================
-- DOMAIN 9: SCHEDULING (2)
-- ============================================================
CREATE TABLE appointments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  location_id INTEGER NOT NULL,
  rma_id INTEGER DEFAULT NULL,
  customer_id INTEGER DEFAULT NULL,
  technician_id INTEGER DEFAULT NULL,
  scheduled_at TIMESTAMP NOT NULL,
  duration_min INTEGER DEFAULT 30,
  type VARCHAR(18) DEFAULT 'drop_off',
  status VARCHAR(19) DEFAULT 'pending',
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP DEFAULT NULL,
  FOREIGN KEY (location_id) REFERENCES locations(id),
  FOREIGN KEY (rma_id) REFERENCES rma_requests(id) ON DELETE SET NULL,
  FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL,
  FOREIGN KEY (technician_id) REFERENCES users(id) ON DELETE SET NULL,
  CHECK (type IN ('drop_off','pickup','callback')),
  CHECK (status IN ('pending','confirmed','completed','cancelled','no_show'))
);

CREATE TABLE technician_schedules (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL,
  location_id INTEGER NOT NULL,
  day_of_week SMALLINT NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  is_active SMALLINT DEFAULT 1,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (location_id) REFERENCES locations(id)
);

-- ============================================================
-- DOMAIN 10: INVOICING & BILLING (5)
-- ============================================================
CREATE TABLE vat_rates (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label VARCHAR(60) NOT NULL,
  rate DECIMAL(5,2) NOT NULL,
  is_default SMALLINT DEFAULT 0
);

CREATE TABLE invoices (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rma_id INTEGER DEFAULT NULL,
  location_id INTEGER NOT NULL,
  customer_id INTEGER DEFAULT NULL,
  partner_id INTEGER DEFAULT NULL,
  created_by INTEGER DEFAULT NULL,
  invoice_number VARCHAR(50) NOT NULL UNIQUE,
  type VARCHAR(21) DEFAULT 'invoice',
  status VARCHAR(19) DEFAULT 'draft',
  subtotal DECIMAL(10,2) DEFAULT 0.00,
  vat_amount DECIMAL(10,2) DEFAULT 0.00,
  total DECIMAL(10,2) DEFAULT 0.00,
  currency VARCHAR(3) DEFAULT 'EUR',
  notes TEXT,
  pdf_path VARCHAR(500),
  due_date DATE DEFAULT NULL,
  paid_at TIMESTAMP DEFAULT NULL,
  sent_at TIMESTAMP DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP DEFAULT NULL,
  FOREIGN KEY (rma_id) REFERENCES rma_requests(id) ON DELETE SET NULL,
  FOREIGN KEY (location_id) REFERENCES locations(id),
  FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL,
  FOREIGN KEY (partner_id) REFERENCES partners(id) ON DELETE SET NULL,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CHECK (type IN ('invoice','credit_note','proforma')),
  CHECK (status IN ('draft','sent','paid','overdue','cancelled'))
);

CREATE TABLE invoice_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id INTEGER NOT NULL,
  description VARCHAR(255) NOT NULL,
  quantity DECIMAL(8,2) DEFAULT 1,
  unit_price DECIMAL(10,2) NOT NULL,
  vat_rate_id INTEGER DEFAULT NULL,
  vat_amount DECIMAL(10,2) DEFAULT 0.00,
  total DECIMAL(10,2) NOT NULL,
  part_id INTEGER DEFAULT NULL,
  sort_order SMALLINT DEFAULT 0,
  FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE,
  FOREIGN KEY (vat_rate_id) REFERENCES vat_rates(id) ON DELETE SET NULL,
  FOREIGN KEY (part_id) REFERENCES parts(id) ON DELETE SET NULL
);

CREATE TABLE payments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id INTEGER NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  method VARCHAR(23) DEFAULT 'bank_transfer',
  reference VARCHAR(150),
  paid_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  recorded_by INTEGER DEFAULT NULL,
  notes TEXT,
  FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE,
  FOREIGN KEY (recorded_by) REFERENCES users(id) ON DELETE SET NULL,
  CHECK (method IN ('cash','card','bank_transfer','other'))
);

CREATE TABLE accounting_exports (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  location_id INTEGER DEFAULT NULL,
  exported_by INTEGER DEFAULT NULL,
  format VARCHAR(18) NOT NULL,
  date_from DATE,
  date_to DATE,
  file_path VARCHAR(500),
  record_count INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE SET NULL,
  FOREIGN KEY (exported_by) REFERENCES users(id) ON DELETE SET NULL,
  CHECK (format IN ('pantheon','sap','xls','csv'))
);

-- ============================================================
-- DOMAIN 11: SLA & CONTRACTS (3)
-- ============================================================
CREATE TABLE sla_rules (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  response_hrs INTEGER DEFAULT 24,
  resolution_hrs INTEGER DEFAULT 72,
  applies_to VARCHAR(25) DEFAULT 'all',
  priority VARCHAR(16) DEFAULT 'normal',
  notify_on_breach SMALLINT DEFAULT 1,
  is_active SMALLINT DEFAULT 1,
  CHECK (applies_to IN ('all','warranty','out_of_warranty','partner')),
  CHECK (priority IN ('low','normal','high','urgent'))
);

CREATE TABLE contract_sla_rules (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contract_id INTEGER NOT NULL,
  name VARCHAR(150),
  response_hrs INTEGER DEFAULT 8,
  resolution_hrs INTEGER DEFAULT 24,
  device_category_id INTEGER DEFAULT NULL,
  FOREIGN KEY (contract_id) REFERENCES service_contracts(id) ON DELETE CASCADE,
  FOREIGN KEY (device_category_id) REFERENCES device_categories(id) ON DELETE SET NULL
);

CREATE TABLE sla_breaches (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rma_id INTEGER NOT NULL,
  sla_rule_id INTEGER DEFAULT NULL,
  breach_type VARCHAR(20) NOT NULL,
  due_at TIMESTAMP NOT NULL,
  breached_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  notified SMALLINT DEFAULT 0,
  FOREIGN KEY (rma_id) REFERENCES rma_requests(id) ON DELETE CASCADE,
  CHECK (breach_type IN ('response','resolution'))
);

-- ============================================================
-- DOMAIN 12: NOTIFICATIONS (2)
-- ============================================================
CREATE TABLE notification_templates (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(100) NOT NULL,
  channel VARCHAR(18) NOT NULL,
  lang VARCHAR(10) DEFAULT 'en',
  subject VARCHAR(255),
  body TEXT NOT NULL,
  is_active SMALLINT DEFAULT 1,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CHECK (channel IN ('email','whatsapp','sms'))
);

CREATE TABLE notification_log (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rma_id INTEGER DEFAULT NULL,
  user_id INTEGER DEFAULT NULL,
  channel VARCHAR(18) NOT NULL,
  recipient VARCHAR(150),
  template_code VARCHAR(100),
  status VARCHAR(19) DEFAULT 'queued',
  error TEXT,
  sent_at TIMESTAMP DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (rma_id) REFERENCES rma_requests(id) ON DELETE SET NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  CHECK (channel IN ('email','whatsapp','sms')),
  CHECK (status IN ('queued','sent','delivered','failed'))
);

-- ============================================================
-- DOMAIN 13: CUSTOMER EXPERIENCE (3)
-- ============================================================
CREATE TABLE csat_surveys (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rma_id INTEGER NOT NULL UNIQUE,
  sent_at TIMESTAMP DEFAULT NULL,
  channel VARCHAR(18) DEFAULT 'whatsapp',
  token VARCHAR(64) NOT NULL UNIQUE,
  responded_at TIMESTAMP DEFAULT NULL,
  FOREIGN KEY (rma_id) REFERENCES rma_requests(id) ON DELETE CASCADE,
  CHECK (channel IN ('whatsapp','email'))
);

CREATE TABLE csat_responses (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  survey_id INTEGER NOT NULL,
  score SMALLINT NOT NULL,
  comment TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (survey_id) REFERENCES csat_surveys(id) ON DELETE CASCADE
);

CREATE TABLE tracking_visibility_settings (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role VARCHAR(18) DEFAULT 'all',
  field_key VARCHAR(60) NOT NULL,
  is_visible SMALLINT DEFAULT 1,
  updated_by INTEGER DEFAULT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL,
  CHECK (role IN ('customer','partner','all'))
);

-- ============================================================
-- DOMAIN 14: VENDOR INTEGRATION (5)
-- ============================================================
CREATE TABLE vendors (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  slug VARCHAR(60) NOT NULL UNIQUE,
  logo_path VARCHAR(500),
  contact VARCHAR(255),
  is_active SMALLINT DEFAULT 1
);

CREATE TABLE vendor_adapters (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vendor_id INTEGER NOT NULL UNIQUE,
  adapter_class VARCHAR(150) NOT NULL,
  endpoint_url VARCHAR(500),
  auth_type VARCHAR(17) DEFAULT 'api_key',
  credentials TEXT,
  sync_mode VARCHAR(16) DEFAULT 'both',
  is_active SMALLINT DEFAULT 0,
  last_tested_at TIMESTAMP DEFAULT NULL,
  FOREIGN KEY (vendor_id) REFERENCES vendors(id) ON DELETE CASCADE,
  CHECK (auth_type IN ('oauth2','api_key','basic','custom')),
  CHECK (sync_mode IN ('auto','manual','both'))
);

-- Per-user overrides for vendor credentials (e.g. each Apple-certified
-- technician has their own GSX bearer token; reception just uses the
-- shop-wide lookup account from vendor_adapters).
CREATE TABLE user_vendor_credentials (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL,
  vendor_id INTEGER NOT NULL,
  credentials TEXT NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id)   REFERENCES users(id)   ON DELETE CASCADE,
  FOREIGN KEY (vendor_id) REFERENCES vendors(id) ON DELETE CASCADE
);

CREATE TABLE vendor_rma_submissions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rma_id INTEGER NOT NULL,
  vendor_id INTEGER NOT NULL,
  vendor_ref VARCHAR(150),
  ra_number VARCHAR(150),
  status VARCHAR(100),
  submitted_at TIMESTAMP DEFAULT NULL,
  last_updated_at TIMESTAMP DEFAULT NULL,
  submitted_by INTEGER DEFAULT NULL,
  FOREIGN KEY (rma_id) REFERENCES rma_requests(id) ON DELETE CASCADE,
  FOREIGN KEY (vendor_id) REFERENCES vendors(id),
  FOREIGN KEY (submitted_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE vendor_sync_log (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vendor_id INTEGER NOT NULL,
  rma_id INTEGER DEFAULT NULL,
  action VARCHAR(60),
  request TEXT,
  response TEXT,
  http_status INTEGER,
  success SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (vendor_id) REFERENCES vendors(id) ON DELETE CASCADE,
  FOREIGN KEY (rma_id) REFERENCES rma_requests(id) ON DELETE SET NULL
);

CREATE TABLE vendor_warranty_cache (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vendor_id INTEGER NOT NULL,
  serial_number VARCHAR(100) NOT NULL,
  status VARCHAR(21) DEFAULT 'unknown',
  expiry_date DATE DEFAULT NULL,
  raw_response TEXT,
  cached_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMP NOT NULL,
  FOREIGN KEY (vendor_id) REFERENCES vendors(id) ON DELETE CASCADE,
  CHECK (status IN ('covered','not_covered','expired','unknown'))
);

-- ============================================================
-- DOMAIN 15: ADMIN PERMISSIONS (4)
-- ============================================================
CREATE TABLE permissions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  module VARCHAR(60) NOT NULL,
  action VARCHAR(60) NOT NULL,
  label VARCHAR(150) NOT NULL,
  description VARCHAR(255),
  sort_order INTEGER DEFAULT 0
);

CREATE TABLE permission_presets (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  description VARCHAR(255),
  created_by INTEGER DEFAULT NULL,
  is_system SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE permission_preset_items (
  preset_id INTEGER NOT NULL,
  permission_id INTEGER NOT NULL,
  PRIMARY KEY (preset_id, permission_id),
  FOREIGN KEY (preset_id) REFERENCES permission_presets(id) ON DELETE CASCADE,
  FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE
);

CREATE TABLE admin_profiles (
  user_id INTEGER PRIMARY KEY,
  preset_id INTEGER DEFAULT NULL,
  overrides JSONB DEFAULT NULL,
  location_ids JSONB DEFAULT NULL,
  created_by INTEGER DEFAULT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (preset_id) REFERENCES permission_presets(id) ON DELETE SET NULL,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);

-- ============================================================
-- DOMAIN 16: SYSTEM (4)
-- ============================================================
CREATE TABLE audit_log (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER DEFAULT NULL,
  action VARCHAR(100) NOT NULL,
  entity_type VARCHAR(60),
  entity_id INTEGER DEFAULT NULL,
  old_values JSONB DEFAULT NULL,
  new_values JSONB DEFAULT NULL,
  ip_address VARCHAR(45),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE settings (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  location_id INTEGER DEFAULT NULL,
  key_name VARCHAR(100) NOT NULL,
  value TEXT,
  type VARCHAR(16) DEFAULT 'string',
  group_name VARCHAR(60) DEFAULT 'general',
  updated_by INTEGER DEFAULT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CHECK (type IN ('string','int','bool','json'))
);

CREATE TABLE languages (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(10) NOT NULL UNIQUE,
  name VARCHAR(60) NOT NULL,
  is_active SMALLINT DEFAULT 1,
  is_default SMALLINT DEFAULT 0
);

CREATE TABLE themes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(30) NOT NULL UNIQUE,
  name VARCHAR(60) NOT NULL,
  css_class VARCHAR(60),
  is_active SMALLINT DEFAULT 1
);

-- ============================================================
-- DEFERRED FOREIGN KEYS (cross-domain references)
-- ============================================================

ALTER TABLE partners
  ADD FOREIGN KEY (default_courier_id) REFERENCES couriers(id) ON DELETE SET NULL;

ALTER TABLE device_brands
  ADD FOREIGN KEY (vendor_id) REFERENCES vendors(id) ON DELETE SET NULL;

ALTER TABLE device_models
  ADD FOREIGN KEY (vendor_id) REFERENCES vendors(id) ON DELETE SET NULL;

ALTER TABLE rma_requests
  ADD FOREIGN KEY (vendor_id) REFERENCES vendors(id) ON DELETE SET NULL,
  ADD FOREIGN KEY (sla_rule_id) REFERENCES sla_rules(id) ON DELETE SET NULL;

ALTER TABLE parts
  ADD FOREIGN KEY (vat_rate_id) REFERENCES vat_rates(id) ON DELETE SET NULL;

-- ============================================================
-- SEED DATA
-- ============================================================

INSERT INTO languages (code, name, is_active, is_default) VALUES
  ('en', 'English', 1, 1),
  ('me', 'Crnogorski', 1, 0);

INSERT INTO themes (code, name, css_class) VALUES
  ('midnight', 'Midnight', 'theme-midnight'),
  ('dark',     'Dark',     'theme-dark'),
  ('ocean',    'Ocean',    'theme-ocean'),
  ('focus',    'Focus',    'theme-focus');

INSERT INTO vat_rates (label, rate, is_default) VALUES
  ('Standard 21%', 21.00, 1),
  ('Reduced 7%',    7.00, 0),
  ('Exempt 0%',     0.00, 0);

INSERT INTO rma_statuses (code, label, label_me, color, sort_order, is_terminal, is_system) VALUES
  ('draft',             'Draft',              'Nacrt',             '#888780', 1,  0, 1),
  ('submitted',         'Submitted',          'Podneseno',         '#378ADD', 2,  0, 1),
  ('awaiting_device',   'Awaiting device',    'Čeka se uredjaj',    '#EF9F27', 3,  0, 1),
  ('device_received',   'Device received',    'Uredjaj primljen',   '#1D9E75', 4,  0, 1),
  ('in_diagnosis',      'In diagnosis',       'Na dijagnostici',   '#7F77DD', 5,  0, 1),
  ('awaiting_parts',    'Awaiting parts',     'Čeka se dio',       '#EF9F27', 6,  0, 1),
  ('in_repair',         'In repair',          'Na popravci',       '#7F77DD', 7,  0, 1),
  ('awaiting_approval', 'Awaiting approval',  'Čeka se odobrenje', '#EF9F27', 8,  0, 1),
  ('repaired',          'Repaired',           'Popravljeno',       '#1D9E75', 9,  0, 1),
  ('dispatched',        'Dispatched',         'Otpremljeno',       '#378ADD', 10, 0, 1),
  ('closed',            'Closed',             'Zatvoreno',         '#3B6D11', 11, 1, 1),
  ('cancelled',         'Cancelled',          'Otkazano',          '#A32D2D', 12, 1, 1),
  ('unrepairable',      'Unrepairable',       'Nepopravljivo',     '#A32D2D', 13, 1, 1);

INSERT INTO repair_statuses (code, label, label_me, color, sort_order, is_terminal) VALUES
  ('pending',     'Pending',     'Na čekanju', '#888780', 1, 0),
  ('in_progress', 'In progress', 'U toku',     '#7F77DD', 2, 0),
  ('on_hold',     'On hold',     'Pauzirano',  '#EF9F27', 3, 0),
  ('completed',   'Completed',   'Završeno',   '#1D9E75', 4, 1),
  ('cancelled',   'Cancelled',   'Otkazano',   '#A32D2D', 5, 1);

INSERT INTO security_policies
  (role, require_2fa, allowed_2fa_channels, max_login_attempts, lockout_minutes, password_min_length, session_timeout_min, force_2fa_new_device)
VALUES
  ('super_admin', 1, 'email,whatsapp,sms', 5, 30, 12, 480,  1),
  ('admin',       1, 'email,whatsapp,sms', 5, 30, 10, 480,  1),
  ('reception',  0, 'email,sms',          5, 30, 10, 480,  0),
  ('technician', 0, 'email',             5, 30, 8,  600,  0),
  ('partner',    1, 'email,whatsapp,sms', 5, 30, 10, 480,  1);

INSERT INTO settings (key_name, value, type, group_name) VALUES
  ('app_name',          'Integra RMS', 'string', 'general'),
  ('app_url',           '',            'string', 'general'),
  ('default_lang',      'en',          'string', 'general'),
  ('img_max_width',     '1920',        'int',    'media'),
  ('img_max_height',    '1920',        'int',    'media'),
  ('img_quality',       '85',          'int',    'media'),
  ('img_thumb_size',    '400',         'int',    'media'),
  ('img_max_upload_mb', '20',          'int',    'media'),
  ('retention_months',  '60',          'int',    'data'),
  ('whatsapp_enabled',  '0',           'bool',   'integrations'),
  ('ai_enabled',        '0',           'bool',   'integrations'),
  ('smtp_host',         '',            'string', 'email'),
  ('smtp_port',         '587',         'int',    'email'),
  ('smtp_user',         '',            'string', 'email'),
  ('smtp_from',         '',            'string', 'email'),
  -- SMS gateway (set sms_provider to 'twilio', 'clickatell' or 'custom')
  ('sms_provider',             '',     'string', 'integrations'),
  ('sms_twilio_sid',           '',     'string', 'integrations'),
  ('sms_twilio_token',         '',     'string', 'integrations'),
  ('sms_twilio_from',          '',     'string', 'integrations'),
  ('sms_clickatell_apikey',    '',     'string', 'integrations'),
  ('sms_clickatell_from',      '',     'string', 'integrations'),
  ('sms_custom_url',           '',     'string', 'integrations'),
  ('sms_custom_auth_header',   '',     'string', 'integrations'),
  ('sms_custom_to_field',      'to',   'string', 'integrations'),
  ('sms_custom_text_field',    'text', 'string', 'integrations'),
  ('sms_custom_extra',         '',     'string', 'integrations'),
  ('sms_custom_json',          '0',    'bool',   'integrations'),
  -- WhatsApp via Meta Cloud API
  ('whatsapp_provider',        'meta',             'string', 'integrations'),
  ('whatsapp_meta_phone_id',   '',                 'string', 'integrations'),
  ('whatsapp_meta_token',      '',                 'string', 'integrations'),
  ('whatsapp_meta_template',   'otp_verification', 'string', 'integrations'),
  ('whatsapp_meta_lang',       'en',               'string', 'integrations'),
  ('whatsapp_meta_version',    'v20.0',            'string', 'integrations');

INSERT INTO permissions (module, action, label, sort_order) VALUES
  ('rma',          'view',    'View RMAs',             1),
  ('rma',          'create',  'Create RMA',            2),
  ('rma',          'edit',    'Edit RMA',              3),
  ('rma',          'delete',  'Delete RMA',            4),
  ('rma',          'assign',  'Assign technician',     5),
  ('repair',       'view',    'View repair jobs',      10),
  ('repair',       'create',  'Create repair job',     11),
  ('repair',       'edit',    'Edit repair job',       12),
  ('parts',        'view',    'View parts',            20),
  ('parts',        'create',  'Add parts',             21),
  ('parts',        'edit',    'Edit parts',            22),
  ('parts',        'delete',  'Delete parts',          23),
  ('invoicing',    'view',    'View invoices',         30),
  ('invoicing',    'create',  'Create invoice',        31),
  ('invoicing',    'edit',    'Edit invoice',          32),
  ('invoicing',    'export',  'Export accounting',     33),
  ('customers',    'view',    'View customers',        40),
  ('customers',    'create',  'Add customer',          41),
  ('customers',    'edit',    'Edit customer',         42),
  ('partners',     'view',    'View partners',         50),
  ('partners',     'edit',    'Edit partners',         51),
  ('users',        'view',    'View users',            60),
  ('users',        'create',  'Add users',             61),
  ('users',        'edit',    'Edit users',            62),
  ('reports',      'view',    'View reports',          70),
  ('reports',      'export',  'Export reports',        71),
  ('settings',     'view',    'View settings',         80),
  ('settings',     'edit',    'Edit settings',         81),
  ('delivery',     'view',    'View shipments',        90),
  ('delivery',     'edit',    'Manage shipments',      91),
  ('appointments', 'view',    'View appointments',     100),
  ('appointments', 'manage',  'Manage appointments',   101);

INSERT INTO permission_presets (name, description, is_system) VALUES
  ('Operations Admin', 'RMA, repair, parts, delivery — no billing or user management', 1),
  ('Billing Admin',    'Invoicing, payments, accounting export — no repair access',    1),
  ('Read-only',        'View-only access across all modules',                          1);

-- ============================================================
-- DOMAIN 11: GOODS RECEIPTS, INVENTORY COUNTS, EVIDENCE, STOCK
-- (tables referenced by controllers but added post-initial schema)
-- ============================================================

-- supplier_sku is now part of the CREATE TABLE parts definition above.
-- (The ALTER here was needed for older DBs; no-op on fresh install.)
CREATE TABLE goods_receipts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supplier_id INTEGER NOT NULL,
  location_id INTEGER NOT NULL,
  reference VARCHAR(100) DEFAULT '',
  freight_cost DECIMAL(12,2) DEFAULT 0,
  default_margin_pct DECIMAL(6,2) DEFAULT 0,
  notes TEXT,
  status VARCHAR(19) NOT NULL DEFAULT 'draft',
  created_by INTEGER DEFAULT NULL,
  confirmed_at TIMESTAMP DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (supplier_id) REFERENCES suppliers(id),
  FOREIGN KEY (location_id) REFERENCES locations(id),
  FOREIGN KEY (created_by)  REFERENCES users(id) ON DELETE SET NULL,
  CHECK (status IN ('draft','confirmed','cancelled'))
);

CREATE TABLE goods_receipt_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  receipt_id INTEGER NOT NULL,
  part_id INTEGER DEFAULT NULL,
  part_name_raw VARCHAR(255) DEFAULT '',
  sku_raw VARCHAR(100) DEFAULT '',
  quantity INTEGER NOT NULL DEFAULT 1,
  supplier_price DECIMAL(12,4) DEFAULT 0,
  customs_duty_pct DECIMAL(6,2) DEFAULT 0,
  cost_price DECIMAL(12,4) DEFAULT 0,
  margin_pct DECIMAL(6,2) DEFAULT 0,
  unit_price DECIMAL(12,2) DEFAULT 0,
  unit_price_override DECIMAL(12,2) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (receipt_id) REFERENCES goods_receipts(id) ON DELETE CASCADE,
  FOREIGN KEY (part_id)    REFERENCES parts(id) ON DELETE SET NULL
);

CREATE TABLE inventory_counts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reference VARCHAR(30) DEFAULT NULL,  -- document number, e.g. POP-2026-0001
  location_id INTEGER NOT NULL,
  started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR(19) NOT NULL DEFAULT 'active',
  created_by INTEGER DEFAULT NULL,
  confirmed_by INTEGER DEFAULT NULL,
  confirmed_at TIMESTAMP DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (location_id)  REFERENCES locations(id),
  FOREIGN KEY (created_by)   REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (confirmed_by) REFERENCES users(id) ON DELETE SET NULL,
  CHECK (status IN ('active','confirmed','cancelled'))
);

CREATE TABLE inventory_count_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  count_id INTEGER NOT NULL,
  part_id INTEGER NOT NULL,
  system_qty INT NOT NULL DEFAULT 0,
  counted_qty INT DEFAULT NULL,
  variance INT GENERATED ALWAYS AS (COALESCE(counted_qty, 0) - system_qty) STORED,
  note VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (count_id) REFERENCES inventory_counts(id) ON DELETE CASCADE,
  FOREIGN KEY (part_id)  REFERENCES parts(id) ON DELETE CASCADE
);

CREATE TABLE repair_evidence (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  repair_job_id INTEGER DEFAULT NULL,
  rma_id INTEGER DEFAULT NULL,
  stage VARCHAR(19) NOT NULL DEFAULT 'repair',
  filename VARCHAR(500) NOT NULL,
  original_name VARCHAR(255) DEFAULT NULL,
  file_size INTEGER DEFAULT 0,
  uploaded_by INTEGER DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP DEFAULT NULL,
  FOREIGN KEY (repair_job_id) REFERENCES repair_jobs(id) ON DELETE CASCADE,
  FOREIGN KEY (rma_id)        REFERENCES rma_requests(id) ON DELETE CASCADE,
  FOREIGN KEY (uploaded_by)   REFERENCES users(id) ON DELETE SET NULL,
  CHECK (stage IN ('reception','repair'))
);

CREATE TABLE repair_evidence_tokens (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token VARCHAR(64) NOT NULL UNIQUE,
  repair_job_id INTEGER DEFAULT NULL,
  rma_id INTEGER DEFAULT NULL,
  stage VARCHAR(19) NOT NULL DEFAULT 'repair',
  expires_at TIMESTAMP NOT NULL,
  visited_at TIMESTAMP DEFAULT NULL,
  completed_at TIMESTAMP DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (repair_job_id) REFERENCES repair_jobs(id) ON DELETE CASCADE,
  FOREIGN KEY (rma_id)        REFERENCES rma_requests(id) ON DELETE CASCADE,
  CHECK (stage IN ('reception','repair'))
);

CREATE TABLE sku_sequences (
  category_id INTEGER NOT NULL PRIMARY KEY,
  last_seq INTEGER NOT NULL DEFAULT 0,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (category_id) REFERENCES device_categories(id) ON DELETE CASCADE
);

CREATE TABLE stock_movements (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  part_id INTEGER NOT NULL,
  location_id INTEGER NOT NULL,
  type VARCHAR(22) NOT NULL,
  quantity INT NOT NULL,
  reference_type VARCHAR(50) DEFAULT NULL,
  reference_id INTEGER DEFAULT NULL,
  reason VARCHAR(255) DEFAULT NULL,
  created_by INTEGER DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (part_id)     REFERENCES parts(id) ON DELETE CASCADE,
  FOREIGN KEY (location_id) REFERENCES locations(id),
  FOREIGN KEY (created_by)  REFERENCES users(id) ON DELETE SET NULL,
  CHECK (type IN ('in','out','receive','use','adjust','reserve','release','transfer_in','transfer_out'))
);

-- ============================================================
-- DOMAIN 17: SIGNATURES & ROLE PERMISSIONS
-- Added here from migrations so a fresh install matches a migrated one.
-- ============================================================
CREATE TABLE rma_signatures (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rma_id INTEGER NOT NULL,
  token VARCHAR(64) NOT NULL UNIQUE,
  filename VARCHAR(500) DEFAULT NULL,
  expires_at TIMESTAMP NOT NULL,
  visited_at TIMESTAMP DEFAULT NULL,
  signed_at TIMESTAMP DEFAULT NULL,
  signer_ip VARCHAR(45) DEFAULT NULL,
  user_agent VARCHAR(500) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP DEFAULT NULL,
  FOREIGN KEY (rma_id) REFERENCES rma_requests(id) ON DELETE CASCADE
);

CREATE TABLE signing_stations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  station_key VARCHAR(64) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL,
  location_id INTEGER NOT NULL,
  is_active SMALLINT DEFAULT 1,
  last_poll_at TIMESTAMP DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE CASCADE
);

-- Editable role -> permission grants (Settings → Permissions).
-- Super Admin is always full-access and is never stored here.
CREATE TABLE role_permissions (
  role VARCHAR(30) NOT NULL,
  module VARCHAR(50) NOT NULL,
  action VARCHAR(30) NOT NULL,
  PRIMARY KEY (role, module, action)
);

INSERT INTO role_permissions (role, module, action) VALUES
  ('reception','rma','view'),('reception','rma','create'),('reception','rma','edit'),
  ('reception','repair','view'),
  ('reception','customers','view'),('reception','customers','create'),('reception','customers','edit'),
  ('reception','partners','view'),('reception','suppliers','view'),
  ('reception','reports','view'),
  ('technician','rma','view'),('technician','rma','edit'),
  ('technician','repair','view'),('technician','repair','create'),('technician','repair','edit'),
  ('technician','parts','view'),
  ('technician','shipments','view'),('technician','shipments','edit'),
  ('technician','customers','view'),
  ('technician','reports','view'),
  ('partner','rma','view'),('partner','rma','create'),
  ('partner','shipments','view'),
  ('partner','customers','view'),
  ('admin','rma','view'),('admin','rma','create'),('admin','rma','edit'),
  ('admin','repair','view'),('admin','repair','create'),('admin','repair','edit'),
  ('admin','parts','view'),('admin','parts','create'),('admin','parts','edit'),('admin','parts','delete'),
  ('admin','shipments','view'),('admin','shipments','create'),('admin','shipments','edit'),
  ('admin','customers','view'),('admin','customers','create'),('admin','customers','edit'),
  ('admin','partners','view'),('admin','partners','edit'),
  ('admin','suppliers','view'),('admin','suppliers','edit'),
  ('admin','reports','view'),
  ('admin','invoicing','view'),
  ('admin','settings','view'),('admin','settings','edit'),
  ('admin','preferences','theme'),('admin','preferences','lang'),('admin','preferences','integrations');

-- Indexes (inline in MySQL, standalone in Postgres)
CREATE INDEX locations_idx_code ON locations (code);
CREATE INDEX auth_attempts_idx_identifier ON auth_attempts (identifier);
CREATE INDEX auth_attempts_idx_ip ON auth_attempts (ip_address);
CREATE INDEX auth_attempts_idx_created ON auth_attempts (created_at);
CREATE INDEX auth_log_idx_user ON auth_log (user_id);
CREATE INDEX auth_log_idx_created ON auth_log (created_at);
CREATE UNIQUE INDEX trusted_devices_uq_user_device ON trusted_devices (user_id, device_hash);
CREATE INDEX customers_idx_email ON customers (email);
CREATE INDEX customers_idx_phone ON customers (phone);
CREATE UNIQUE INDEX partner_users_uq_partner_user ON partner_users (partner_id, user_id);
CREATE UNIQUE INDEX devices_uq_serial ON devices (serial_number);
CREATE INDEX rma_requests_idx_location ON rma_requests (location_id);
CREATE INDEX rma_requests_idx_status ON rma_requests (status_id);
CREATE INDEX rma_requests_idx_customer ON rma_requests (customer_id);
CREATE INDEX rma_requests_idx_partner ON rma_requests (partner_id);
CREATE INDEX rma_requests_idx_rma_number ON rma_requests (rma_number);
CREATE INDEX rma_requests_idx_created ON rma_requests (created_at);
CREATE INDEX parts_idx_parts_brand ON parts (brand_id);
CREATE INDEX parts_idx_parts_category ON parts (category_id);
CREATE INDEX parts_idx_parts_part_group ON parts (part_group_id);
CREATE UNIQUE INDEX parts_stock_uq_part_location ON parts_stock (part_id, location_id);
CREATE UNIQUE INDEX notification_templates_uq_code_channel_lang ON notification_templates (code, channel, lang);
CREATE UNIQUE INDEX tracking_visibility_settings_uq_role_field ON tracking_visibility_settings (role, field_key);
CREATE UNIQUE INDEX user_vendor_credentials_uq_user_vendor ON user_vendor_credentials (user_id, vendor_id);
CREATE UNIQUE INDEX vendor_warranty_cache_uq_vendor_serial ON vendor_warranty_cache (vendor_id, serial_number);
CREATE UNIQUE INDEX permissions_uq_module_action ON permissions (module, action);
CREATE INDEX audit_log_idx_entity ON audit_log (entity_type, entity_id);
CREATE INDEX audit_log_idx_user ON audit_log (user_id);
CREATE INDEX audit_log_idx_created ON audit_log (created_at);
CREATE UNIQUE INDEX settings_uq_location_key ON settings (location_id, key_name);
CREATE INDEX goods_receipts_idx_supplier ON goods_receipts (supplier_id);
CREATE INDEX goods_receipts_idx_location ON goods_receipts (location_id);
CREATE INDEX goods_receipts_idx_status ON goods_receipts (status);
CREATE INDEX goods_receipt_items_idx_receipt ON goods_receipt_items (receipt_id);
CREATE INDEX goods_receipt_items_idx_part ON goods_receipt_items (part_id);
CREATE INDEX inventory_counts_idx_location ON inventory_counts (location_id);
CREATE INDEX inventory_counts_idx_status ON inventory_counts (status);
CREATE INDEX inventory_counts_idx_started ON inventory_counts (started_at);
CREATE INDEX inventory_count_items_idx_count ON inventory_count_items (count_id);
CREATE INDEX inventory_count_items_idx_part ON inventory_count_items (part_id);
CREATE INDEX repair_evidence_idx_repair_job ON repair_evidence (repair_job_id);
CREATE INDEX repair_evidence_idx_rma ON repair_evidence (rma_id);
CREATE INDEX repair_evidence_idx_stage ON repair_evidence (stage);
CREATE INDEX repair_evidence_tokens_idx_expires ON repair_evidence_tokens (expires_at);
CREATE INDEX stock_movements_idx_part ON stock_movements (part_id);
CREATE INDEX stock_movements_idx_location ON stock_movements (location_id);
CREATE INDEX stock_movements_idx_ref ON stock_movements (reference_type, reference_id);
CREATE INDEX rma_signatures_idx_rma ON rma_signatures (rma_id);
CREATE INDEX rma_signatures_idx_expires ON rma_signatures (expires_at);
CREATE INDEX signing_stations_idx_location ON signing_stations (location_id);

-- updated_at triggers (MySQL's ON UPDATE NOW())
CREATE TRIGGER users_touch BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER security_policies_touch BEFORE UPDATE ON security_policies FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER customers_touch BEFORE UPDATE ON customers FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER partners_touch BEFORE UPDATE ON partners FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER service_contracts_touch BEFORE UPDATE ON service_contracts FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER devices_touch BEFORE UPDATE ON devices FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER rma_requests_touch BEFORE UPDATE ON rma_requests FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER rma_comments_touch BEFORE UPDATE ON rma_comments FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER repair_jobs_touch BEFORE UPDATE ON repair_jobs FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER parts_touch BEFORE UPDATE ON parts FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER parts_stock_touch BEFORE UPDATE ON parts_stock FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER purchase_orders_touch BEFORE UPDATE ON purchase_orders FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER delivery_shipments_touch BEFORE UPDATE ON delivery_shipments FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER appointments_touch BEFORE UPDATE ON appointments FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER invoices_touch BEFORE UPDATE ON invoices FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER notification_templates_touch BEFORE UPDATE ON notification_templates FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER tracking_visibility_settings_touch BEFORE UPDATE ON tracking_visibility_settings FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER user_vendor_credentials_touch BEFORE UPDATE ON user_vendor_credentials FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER admin_profiles_touch BEFORE UPDATE ON admin_profiles FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER settings_touch BEFORE UPDATE ON settings FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER goods_receipts_touch BEFORE UPDATE ON goods_receipts FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER inventory_counts_touch BEFORE UPDATE ON inventory_counts FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER sku_sequences_touch BEFORE UPDATE ON sku_sequences FOR EACH ROW EXECUTE FUNCTION touch_updated_at();